In [1]:
a="surjith"
a


'surjith'

In [2]:
a=[23,454,44,221,662,1,33]
a

[23, 454, 44, 221, 662, 1, 33]

In [3]:
a[3]


221

In [4]:
import numpy as np
s=np.array(a)
s

array([ 23, 454,  44, 221, 662,   1,  33])

In [5]:
np.mean(s)

np.float64(205.42857142857142)

In [6]:
np.max(s)


np.int64(662)

In [7]:
np.min(s)

np.int64(1)

In [8]:
np.reshape(s,(1,7))

array([[ 23, 454,  44, 221, 662,   1,  33]])

In [9]:
np.reshape(s,(7,1))

array([[ 23],
       [454],
       [ 44],
       [221],
       [662],
       [  1],
       [ 33]])

In [78]:
b=[10,20,30,10,20,31]
a=[1,3,2,4,6,5]
d=np.array(a)
p=np.array(b)


In [79]:
type(d)
e=np.concatenate((d,p))
e


array([ 1,  3,  2,  4,  6,  5, 10, 20, 30, 10, 20, 31])

In [47]:
np.sort(a)


array([1, 2, 3, 4, 5, 6])

In [73]:
print(np.eye(10,11,1))

[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [80]:
e

array([ 1,  3,  2,  4,  6,  5, 10, 20, 30, 10, 20, 31])

In [81]:
np.argmax(e)

np.int64(11)

In [82]:
print(np.where(e>10))

(array([ 7,  8, 10, 11]),)


In [87]:
print(np.where(e>1))

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]),)


In [96]:
r= np.array([1,  3,  2,  4,  6,  5, 10, 20, 30, 10, 20, 31])
print(r)
type(r)


[ 1  3  2  4  6  5 10 20 30 10 20 31]


numpy.ndarray

In [101]:
print(r[2:8])

[ 2  4  6  5 10 20]


In [109]:
print(r[::2])

[ 1  2  6 10 30 20]


In [128]:
j=np.array([[1,2,3,4,4,1],[10,20,30,70,20,40],[10,20,30,70,50,90],[11,55,22,33,77,55]])

j

array([[ 1,  2,  3,  4,  4,  1],
       [10, 20, 30, 70, 20, 40],
       [10, 20, 30, 70, 50, 90],
       [11, 55, 22, 33, 77, 55]])

In [120]:
print(j[2:3,:])

[[10 20 30 70 50 90]]


In [132]:
print(j[1:,:2])

[[10 20]
 [10 20]
 [11 55]]


In [133]:
print(j[1:,3:])

[[70 20 40]
 [70 50 90]
 [33 77 55]]


In [136]:
print(j[1:,::2])

[[10 30 20]
 [10 30 50]
 [11 22 77]]


In [138]:
print(j[:2,::2])

[[ 1  3  4]
 [10 30 20]]


In [144]:
import pandas as pd
pd

<module 'pandas' from '/usr/local/lib/python3.12/dist-packages/pandas/__init__.py'>

In [148]:
h=pd.read_csv("/content/anime.csv")
h

,anime_id,title,score,rank,popularity,members,synopsis,start_date,end_date,type,episodes,image_url
0,28977,Gintama°,9.05,8,347,680037,"Gintoki, Shinpachi, and Kagura return as the f...",2015-01-01,2016-01-01,TV,51.0,https://cdn.myanimelist.net/images/anime/3/720...
1,57555,Chainsaw Man Movie: Reze-hen,9.18,2,962,282129,Sequel to Chainsaw Man .,2025-01-01,2025-01-01,Movie,1.0,https://cdn.myanimelist.net/images/anime/1763/...
2,11061,Hunter x Hunter (2011),9.03,9,8,3107455,Hunters devote themselves to accomplishing haz...,2011-01-01,2014-01-01,TV,148.0,https://cdn.myanimelist.net/images/anime/1337/...
3,52991,Sousou no Frieren,9.29,1,121,1269074,During their decade-long quest to defeat the D...,2023-01-01,2024-01-01,TV,28.0,https://cdn.myanimelist.net/images/anime/1015/...
4,9969,Gintama',9.02,11,406,601940,"After a one-year hiatus, Shinpachi Shimura ret...",2011-01-01,2012-01-01,TV,51.0,https://cdn.myanimelist.net/images/anime/4/503...
...,...,...,...,...,...,...,...,...,...,...,...,...
9995,1351,Angel Cop,6.05,9994,4755,26983,"Sometime in the future, terrorism in Japan has...",1989-01-01,1994-01-01,OVA,6.0,https://cdn.myanimelist.net/images/anime/1377/...
9996,33339,Zhongguo Jingqi Xiansheng,6.05,9991,10781,3192,A lost form of magic is revived from the Easte...,2014-01-01,2016-01-01,ONA,63.0,https://cdn.myanimelist.net/images/anime/1637/...
9997,2840,Youkoso Lodoss-tou e!,6.05,9988,11348,2710,This movie is the compilation of the 27 mini-p...,1998-01-01,1998-01-01,Movie,1.0,https://cdn.myanimelist.net/images/anime/7/613...
9998,33764,Ying Xiong Bie Nao,6.05,9987,17963,502,The series takes place on a parallel world fil...,2015-01-01,2015-01-01,ONA,13.0,https://cdn.myanimelist.net/images/anime/1013/...
